global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanager:
   - static_configs:
     - targets:
        - alertmanager:9093
scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['0.0.0.0:4443']
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - prometheus:9090
rule_files:
  - rules.yml