# Generated by Django 3.2.7 on 2024-07-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_home_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='home_message',
            name='user',
        ),
    ]
