# Generated by Django 3.2.7 on 2024-07-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20240722_0328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_Message',
        ),
    ]
