# Generated by Django 3.2.7 on 2024-07-22 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_home_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='opponent_type',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='ai', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='opponent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
