# Generated by Django 3.2.7 on 2024-07-22 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20240722_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='won_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='won_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
