# Generated by Django 3.2.7 on 2024-07-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20240722_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
