# Generated by Django 3.2.7 on 2024-07-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_room_opponent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='opp_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='opponent_type',
            field=models.CharField(choices=[('vs Player', 'vs Player'), ('Tournament', 'Tournament'), ('AI', 'AI')], default='ai', max_length=10),
        ),
    ]
