# Generated by Django 3.2.25 on 2024-08-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='The User too lazy to add a Bio', null=True),
        ),
    ]
