# Generated by Django 3.2.25 on 2024-08-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_chats',
            field=models.ManyToManyField(blank=True, related_name='group_members', to='base.ChatGroup'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
