# Generated by Django 3.2.25 on 2024-08-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20240815_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.CharField(max_length=20),
        ),
    ]
