# Generated by Django 3.2.25 on 2024-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_alter_room_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='invitation_link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='opponent_type',
            field=models.CharField(choices=[('vs Player', 'vs Player'), ('Tournament', 'Tournament'), ('AI', 'AI')], default='AI', max_length=10),
        ),
    ]
